### ISSUE TITLE
Question: Does the image need to be that big?

### ISSUE THREAD

**Issue by daKmoR** [NotWoods/maskable#22]
When using an svg it exports an image with the size of 1024x1024px - does it make sense to have it that big?

**Comment by daKmoR** [comment]
The image I got was a 241KB png file 😱

Passing it OxiPNG through with https://squoosh.app/ could make a 40% smaller png.

The question is is why not use WebP? maskable images are only for more "modern" android devices that should support webP right? 🤔. 

If webP is not an option then JPEG would still be way smaller then an png in most cases

**Comment by NotWoods** [comment]
Safari only recently added WebP support, so the app exports PNG files right now so that it can be used from Safari. PNG is also better supported by image editors if you want to do any touch up or minification afterwards.

Admittedly 1024x1024 is too big for most use cases, but I prefer to err on the side of caution because you can shrink the image afterwards. Ideally I'd like to find an algorithm for exporting an SVG, or maybe just add an option to configure the export size.

**Comment by NotWoods** [comment]
Gonna close this because there are now controls for export size

**Comment by tkrotoff** [comment]
@daKmoR 
> JPEG would still be way smaller then an png in most cases

Bad idea: you should never use jpeg for icons.
