### ISSUE TITLE
Exporting multiple sizes

### ISSUE THREAD

**Issue by MatthiasKunnen** [NotWoods/maskable#32]
Would it be possible to add an option that allows choosing the sizes to export? 

Nice tool!

In the meanwhile I'm using:
```bash
for r in 72 96 128 144 152 192 384 512; do
    convert icon-maskable.png -resize $r icon-maskable-${r}x${r}.png
done
```

**Comment by NotWoods** [comment]
I'm happy to add this if anyone has some good UI proposals. :) Throwing on a hacktoberfest label too, although its a bit late in the month.

**Comment by byronalley** [comment]
I'm working on something for this FYI.

**Comment by Yohandah** [comment]
Excuse my ignorance but I don't get it. Why is the export only 196x196 ? Don't you need to specify all the sizes (48x48 72x72 96x96 128x128 256x256 196x196 512x512) in the manifest ?

**Comment by NotWoods** [comment]
Currently, the app exports the largest size it can based on the assets you provide. You can then do additional resizing using another image tool like Squoosh. In your case, the export is 196x196 because your any larger sizes would require upscaling your icons and losing some quality.

The only exception to this is SVG, which is capped at 1024x1024.
