### ISSUE TITLE
Need to preserve tarasparency in png

### ISSUE THREAD

**Issue by budarin** [NotWoods/maskable#77]
Now the application forces you to use a solid color as the background, although the icon is made with transparency

**Comment by NotWoods** [comment]
The application forces use of a solid color because transparent maskable icons don't work. Maskable icons are designed to represent an icon with a background, and using a transparent background means the browser will just fill in the empty space with an arbitrary color. 

See https://css-tricks.com/maskable-icons-android-adaptive-icons-for-your-pwa/ for more details
